### ISSUE TITLE
Question about caption evaluation

### ISSUE THREAD

**Issue by 8reaks** [ch3cook-fdu/Vote2Cap-DETR#5]
Hi,

Where could I find the pretrained weights of 4.1 or 4.2, I have tested the weights provided on huggingface by 4.3. However, they all returned errors as the image shown.

![image](https://github.com/ch3cook-fdu/Vote2Cap-DETR/assets/46956263/b95bcde2-f761-4fad-ad4c-bea7a6894d4d)

**Comment by ch3cook-fdu** [comment]
The error in the image indicates the weights are not properly loaded. This might be caused by different implementation of `GPT2Attention` in different versions of `huggingface transformers`. In my case (`transformers==4.30.2`), the weights for attention bias are always ignored. If you still encounter certain error after installing `transformers==4.30.2`, please try editing [this line](https://github.com/ch3cook-fdu/Vote2Cap-DETR/blob/master/main.py#L206C34-L206C34) into:

```{python}
model.load_state_dict(checkpoint["model"], strict=False)
```

to skip the loading of attention bias.

All the weights for Vote2Cap-DETR could be found under [this folder](https://huggingface.co/CH3COOK/Vote2Cap-DETR-weights/tree/main/vote2cap-detr).

**Comment by 8reaks** [comment]
Thank you. It works! But for weights of Vote2Cap-DETR++, it still has an error of 

"RuntimeError: Error(s) in loading state_dict for CaptionNet:
	size mismatch for captioner.transformer.transformer.wpe.weight: copying a param with shape torch.Size([128, 256]) from checkpoint, the shape in current model is torch.Size([64, 256])." 

Moreover, for the caption case, when I look into the evaluation results of Vote2Cap-DETR and visualize it, it seems have much fewer boundingbox with caption than the ground truth. Is the result correct?

![image](https://github.com/ch3cook-fdu/Vote2Cap-DETR/assets/46956263/2ce2976f-99c8-4efe-8d0b-09c493099974)

**Comment by ch3cook-fdu** [comment]
Sorry that I have not currently released these codes for the Vote2Cap-DETR++ model, thus the weights currently cannot be properly loaded.

As for the visualization, this is not usual. Please consider using the following commands:

```{bash}
python demo.py --use_color --use_normal --dataset scene_scanrefer --vocabulary scanrefer --use_beam_search --detector detector_Vote2Cap_DETR --captioner captioner_dcc --test_ckpt path_to_your_weight.pth
```

This will generate some `.json` files that can be used to visualize the predictions. You can use the tools in this [repo](https://github.com/ch3cook-fdu/3d-pc-box-viz) to help visualize the box estimations.

**Comment by 8reaks** [comment]
Thank you so much!
